### ISSUE TITLE
Including phosphorus patterns?

### ISSUE THREAD

**Issue by maxentile** [openforcefield/openff-recharge#109]
Hi @SimonBoothroyd !

Quick question: I was curious why these phosphorus patterns are commented out in the conversion script: https://github.com/openforcefield/openff-recharge/blob/2a10e8c5bb46178b8a5cd92e43bb1195e6c9ecaf/scripts/convert-am1-bcc/convert.py#L130-L133 

Do you think it would be fine to uncomment these, or is there a pitfall to be aware of? (I didn't see a prior discussion of this in a brief search of the repository.)

Best regards,
Josh

**Comment by SimonBoothroyd** [comment]
Hey @maxentile,

I'm sorry for the delayed response - I've been preparing to start a new job so things have been pretty busy!

> I was curious why these phosphorus patterns are commented out in the conversion script:

I simply hadn't had enough time to properly port these into SMIRKS just yet and ensure they are fully tested! 

The easy bit is mapping the phosphorous codes into SMIRKS patterns which is the lines commented out. The trickier ( / tedious) bit is then updating the other codes (BCCs involving a 'dative' bond, nitrogen with a highly delocalized lone pair etc) to work alongside them. 

> Do you think it would be fine to uncomment these, or is there a pitfall to be aware of?

If you're refitting all the charges then you should be fine minus any chemical perception issues. If you need these to match closely to the original AM1BCC model or the canonical OE implementation of it however then it's likely that just uncommenting these lines won't be enough, and the other SMIRKS will need a bit of tweaking!

**Comment by maxentile** [comment]
Thanks @SimonBoothroyd for the context and advice!

This all makes sense. Will proceed with caution about the issues you mention if porting these in the future.
