### ISSUE TITLE
Virtual site handling needs updating

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-recharge#136]
I'm getting this error with virtual sites:

```
File "/lila/data/chodera/lilywang/fit-virtual-sites/02_train-vsites/select-esp-records.py", line 53, in process_molecule
    vsite_assignment_matrix = VirtualSiteGenerator.build_charge_assignment_matrix(
  File "/home/lilywang/miniconda3/envs/fit-virtual-sites/lib/python3.9/site-packages/openff/recharge/charges/vsite.py", line 537, in build_charge_assignment_matrix
    off_molecule, assigned_vsite_keys = cls._apply_virtual_sites(
  File "/home/lilywang/miniconda3/envs/fit-virtual-sites/lib/python3.9/site-packages/openff/recharge/charges/vsite.py", line 424, in _apply_virtual_sites
    parameter_handler.create_openff_virtual_sites(off_topology)
  File "/home/lilywang/miniconda3/envs/fit-virtual-sites/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/parameters.py", line 1120, in __getattr__
    raise AttributeError(
AttributeError: <class 'openff.toolkit.typing.engines.smirnoff.parameters.VirtualSiteHandler'> object has no attribute 'create_openff_virtual_sites'
```

This method no longer exists on the VirtualSiteHandler. I think this behaviour may have moved to interchange? Step 1 is to figure out what `create_openff_virtual_sites` did.

**Comment by mattwthompson** [comment]
The entire virtual site code is broken (https://github.com/openforcefield/openff-recharge/issues/126). The information content has moved to Interchange a la

```python
In [26]: collection = ForceField("opc-1.0.1.offxml").create_interchange(Molecule
    ...: .from_smiles("O").to_topology()).collections['VirtualSites']

In [27]: [*collection.key_map][0].orientation_atom_indices
Out[27]: (0, 1, 2)

In [28]: [*collection.potentials.items()]
Out[28]:
[(PotentialKey associated with handler 'VirtualSites' with id '[#1:2]-[#8X2H2+0:1]-[#1:3] EP once',
  Potential(parameters={'distance': <Quantity(-0.15939833, 'angstrom')>, 'outOfPlaneAngle': <Quantity(0.0, 'degree')>, 'inPlaneAngle': None}, map_key=None))]

```
though things don't line up 1:1 and I didn't get around to updating things. Interchange makes an attempt with virtual sites, like other parameters, to store things in an engine-agnostic way. I don't recall implementing virtual sites in any export but OpenMM, which might have some rough edges yet.

`create_openff_virtual_sites` made virtual site-like objects on `Molecule`s, something that I advocated against on the basis that molecules don't have virtual sites and they only exist after a force field has been applied.

**Comment by lilyminium** [comment]
Right, I see, that makes sense! I like Interchange's approach better. I'll see if I can fix up any of this quickly before downgrading my environment to pre-0.11 -- unfortunately I need to use the vsite code soon.
