### ISSUE TITLE
Single thread psi4 in RESP solver

### ISSUE THREAD

**Issue by GregorySchwing** [openforcefield/openff-recharge#146]
I've been able to get some good preliminary results for small molecules doing geometry optimization with QCEngine and charge assignment using RESP.  Something I've noticed is QCEngine runs psi4 with 8 cores by default, but the interface in this repo runs psi4 with 1 core by default.  For small molecules, this isn't a big problem, but larger molecules are currently taking > 10 minutes, I stopped them eventually.  

I've attached an example.  I have a few related concerns:
1. How do I resolve this warning?  Do I have to worry about it when I'm going from openff molecule to qcschema to openff molecule?  It's caused by code internal to recharge "openff/recharge/charges/library.py:155"
`Warning! Fully mapped SMILES pattern passed to `from_smiles`. The atom map is stored as a property in `Molecule._properties`, but these indices are NOT used to determine atom ordering. To use these indices for atom ordering, use `Molecule.from_mapped_smiles`.`

2.  What are the implications of "allow_undefined_stereo=True" on openff?  
3. How can I increase the number of threads used in psi4 during RESP?

```
smiles="O"
smiles="OC(=O)C(O)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F"
# Imports from the toolkit
from openff.toolkit import ForceField, Molecule, Topology
from openff.units import Quantity, unit
from openff.interchange import Interchange
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdmolfiles

from openff.recharge.charges.library import (
    LibraryChargeCollection,
    LibraryChargeGenerator,
)
from openff.recharge.charges.resp import generate_resp_charge_parameter
from openff.recharge.charges.resp.solvers import IterativeSolver
from openff.recharge.esp import ESPSettings
from openff.recharge.esp.psi4 import Psi4ESPGenerator
from openff.recharge.esp.storage import MoleculeESPRecord
from openff.recharge.grids import MSKGridSettings
from openff.recharge.utilities.molecule import extract_conformers
from openff.recharge.utilities.molecule import smiles_to_molecule
from parmed.formats.registry import load_file
from parmed.formats.mol2 import Mol2File

def embed(mol, seed=None):
    params = AllChem.ETKDGv2()
    if seed is not None:
        params.randomSeed = seed
    else:
        params.randomSeed = 123
    AllChem.EmbedMolecule(mol, params)
    return mol

forcefield = ForceField("openff-2.1.0.offxml")
openff_mol = Molecule.from_smiles(smiles,allow_undefined_stereo=True)
#openff_mol = smiles_to_molecule(smiles)
openff_mol.generate_conformers(n_conformers=1)
"""
rdmol = openff_mol.to_rdkit()
rdmol3D = embed(rdmol,123)
openff_mol_3D = Molecule.from_rdkit(rdmol3D)


interchangeb4 = Interchange.from_smirnoff(
    force_field=forcefield,
    topology=openff_mol_3D.to_topology(),
)
interchangeb4.to_inpcrd("ligandb4.crd")
interchangeb4.to_prmtop("ligandb4.prmtop")
struct = load_file('ligandb4.prmtop', xyz='ligandb4.crd')
Mol2File.write(struct, "ligandb4.mol2")
qcemol = openff_mol_3D.to_qcschema()

"""
qcemol = openff_mol.to_qcschema()


import qcelemental as qcel
print(qcemol)
print(qcemol.geometry)
#print(dir(qcemol))
import qcengine as qcng
import qcelemental as qcel

inp = qcel.models.AtomicInput(
molecule=qcemol,
driver="energy",
model={"method": "SCF", "basis": "sto-3g"},
keywords={"scf_type": "df"}
)

inp = qcel.models.AtomicInput(
    schema_name="qcschema_input",
    schema_version=1,
    molecule=qcemol,
    driver="gradient",
    model={"method": "SCF", "basis": "sto-3g"},
    keywords={"scf_type": "df"},
    
)

ret = qcng.compute(inp, "psi4")
print(ret)
print(ret.return_result)
print(ret.molecule.geometry)
openff_mol_qc = Molecule.from_qcschema(ret.molecule,allow_undefined_stereo=True)
[input_conformer] = extract_conformers(openff_mol_qc)

qc_data_settings = ESPSettings(
    method="hf", basis="6-31G*", grid_settings=MSKGridSettings(),
)

conformer, grid, esp, electric_field = Psi4ESPGenerator.generate(
    openff_mol_qc, input_conformer, qc_data_settings, minimize=True
)

qc_data_record = MoleculeESPRecord.from_molecule(
    openff_mol_qc, conformer, grid, esp, None, qc_data_settings
)

resp_solver = IterativeSolver()
# While by default the iterative approach to finding the set of charges that minimize
# the RESP loss function as described in the original papers is used, others such as
# an experimental one that calls out to SciPy are available, e.g.
# resp_solver = SciPySolver(method="SLSQP")

resp_charge_parameter = generate_resp_charge_parameter(
    [qc_data_record], resp_solver
)
resp_charges = LibraryChargeGenerator.generate(
    openff_mol_qc, LibraryChargeCollection(parameters=[resp_charge_parameter])
)
import numpy
print(f"RESP SMILES         : {resp_charge_parameter.smiles}")
print(f"RESP VALUES (UNIQUE): {resp_charge_parameter.value}")
print("")
print(f"RESP CHARGES        : {numpy.round(resp_charges, 4)}")

print(f"CONFORMER           : {numpy.round(conformer, 4)}")


import numpy as np
from openff.toolkit.topology import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.toolkit.typing.engines.smirnoff.parameters import LibraryChargeHandler


# Assign partial charges from a list-like object
openff_mol_qc.partial_charges = np.asarray(resp_charges.flatten()) * unit.elementary_charge
print(f"MOL CHARGES        : {numpy.round(openff_mol_qc.partial_charges, 4)}")

library_charge_type = LibraryChargeHandler.LibraryChargeType.from_molecule(openff_mol_qc)
forcefield["LibraryCharges"].add_parameter(parameter=library_charge_type)

# Create a PDB file
#writer = rdmolfiles.MolToPDBFile(rdmol3D, "ligand.pdb")
# Load the topology from a PDB file and `Molecule` objects
topology = openff_mol_qc.to_topology()

interchange = Interchange.from_smirnoff(
    force_field=forcefield,
    topology=topology,
)
interchange.to_prmtop("ligand.prmtop")
interchange.to_inpcrd("ligand.crd")
struct = load_file('ligand.prmtop', xyz='ligand.crd')
Mol2File.write(struct, "ligand.mol2")

```

**Comment by mattwthompson** [comment]
1. That internally-thrown warning is genuine and stems from a change to the toolkit that hasn't been updated here yet. I should be able to get that in the next release (#147). Unless atom mapping is important (it probably isn't for the stuff I'm seeing you do) you can ignore this, even though it looks spooky.
2. The key implication is that `Molecule` objects can be created with undefined stereochemistry. Usually MM or QM use cases don't need stereochemistry, but it's relevant in cheminformatics and some biophysics, so the toolkit defaults to requiring it. More here: https://docs.openforcefield.org/projects/toolkit/en/stable/faq.html#im-getting-stereochemistry-errors-when-loading-a-molecule-from-a-smiles-string
3. It looks like Psi4 has an `-n / --nthread` option that could be wired through `Psi4ESPGenerator.generate`. We'd welcome a PR for that, but I'll get to doing it soon one way or another

**Comment by mattwthompson** [comment]
@GregorySchwing the atom mapping warning shouldn't be thrown any more from the `main` branch.

If you want it, we can probably get Psi4 to use multiple threads. Otherwise, I'll probably make a release soon with the existing changes in it.

**Comment by GregorySchwing** [comment]
If you can do it, I'd appreciate it in the meantime as there is an open PR to psi4 (https://github.com/psi4/psi4/issues/2307) to allow ESP grid calculation through the QCSchema exposing the grid generation to the user, instead of going through a wrapper class such as Psi4ESPGenerator.  This would also handle the number of threads, so I wouldn't do a serious overhaul of openff-recharge knowing this functionality will be released in the next psi4 release.

**Comment by mattwthompson** [comment]
The people behind QCEngine and Psi4 are great, but their development timelines are fairly inconsistent so it wouldn't hurt to have it in here. I took a stab at it in #151, without doing any super involved testing. What sort of size molecule should I use testing this?

**Comment by GregorySchwing** [comment]
This (https://comptox.epa.gov/dashboard/chemical/details/DTXSID30758800?list=PFASMASTER) is the molecule which prompted me to open this issue
SMILES: 
`OC(=O)C(O)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F`

**Comment by GregorySchwing** [comment]
Ok. It's basically a long carbon chain of flouride groups, so I expect its extra difficult to get an ESP of.

**Comment by mattwthompson** [comment]
I think these results are sensible, would you agree?

![image](https://github.com/openforcefield/openff-recharge/assets/7935382/732c7c7b-0036-4ee8-80a3-dcb1bcfd25c1)

**Comment by GregorySchwing** [comment]
thats great. thank you

**Comment by mattwthompson** [comment]
Awesome, 0.5.1 builds should be online within the hour
