### ISSUE TITLE
is it possible to allow different tightness parameters?

### ISSUE THREAD

**Issue by yanze039** [openforcefield/openff-recharge#156]
Hi,

I am not sure if I'm cool to post question here. But I notice that the OpenFF RESP documentation website (https://docs.openforcefield.org/projects/recharge/en/stable/users/resp.html) illurstrates that the two-stage resp charge fitting procedure has `b=0.1` for both steps, followed by 3 citations. 

However, things seem more tricky. In Piotr et al (1994)'s paper (https://onlinelibrary.wiley.com/doi/10.1002/jcc.540161106), though they said "A value of 0.1 was found to be appropriate for b." in page 1361, their actual parameter was `b=0.0` as described "In the first stage, a weak hyperbolic restraint (a = 0.0005) to a target value of 0.0 is applied to all heavy atoms." also in page 1361. 

I'm not sure how this difference happens, but I checked the source code of `respgen.F` in `ambertools` out, that the doc in source code file is as follows:
```
.../AmberTools/src/etc/resp.F
...
line 1143
 b) a hyperbolic restraint to a charge of 0.  This gets asymptotic at
c  "large" values, so "large" charges aren't pulled down any stronger
c  than some (reasonable) limiting force.  This is a non-linear
c  weighting function, so the fit procedure is iterative.
c
...
```
They said `b` is fixed at 0.

I noticed that the `b` value in amber RESP tutorial is also fixed without interface to it, but it seems to be fixed in different values. 

and RESP2 paper use the `b=0.0` strategy as well...

Any suggestions on this parameter setting?

**Comment by mattwthompson** [comment]
I'm completely unqualified to give scientific guidance on this question, but with regards to whether or not you can fiddle with the `b` parameter: yes! Here's where that parameter is set, and you can use a development build to do these sorts of experiments: https://github.com/openforcefield/openff-recharge/blob/0.5.1/openff/recharge/charges/resp/_resp.py#L411

Something like this, with your conda environment already activated, is how to get a development build rolling:

```shell
$ git clone git@github.com:openforcefield/openff-recharge.git
$ cd openff-recharge
$ git checkout origin/0.5.1  # or whatever version you were using
$ vi openff/recharge/charges/resp/_resp.py  # or your preferred text editor/IDE
$ python -m pip install -e .
```
Allow me to also route the question to @lilyminium who is likely to know more about the wizardry of RESP (but might not be back in the office until next week)

**Comment by yanze039** [comment]
Thanks for the information!

And sorry for my misunderstanding of the materials, the hyperbolic constraints has the form of 
$ \chi = a \sum{ ( q^2 + b^2 )^(1/2) -b} $
which really means restraining charges towards 0, no matter what value of `b` is ...
