### ISSUE TITLE
Add more VdW Radii and K has incorrect radii

### ISSUE THREAD

**Issue by sef43** [openforcefield/openff-recharge#171]
Hello,

I have found that the selection of vdw_radii available for the RESP calculation is quite small:
https://github.com/openforcefield/openff-recharge/blob/be7a5218d27677504d7c3a2998c71d0b44a9ea90/openff/recharge/utilities/toolkits.py#L182-L196

Particularly I think `Si` should be included.

Also I think 'K' should be 2.75 not 1.75

**Comment by lilyminium** [comment]
Thanks for raising this @sef43 -- I think we've not prioritized elements outside the ones supported by the mainstream OpenFF force fields, but we can certainly expand the radius set -- I'll have a crack at doing so next week if no one else has opened a PR by then :-)
