### ISSUE TITLE
Merz-Singh-Kollman (MSK) shell support for ESP points

### ISSUE THREAD

**Issue by wwilla7** [openforcefield/openff-recharge#83]
Hi,

I would like to request a feature of using a Merz-Singh-Kollman (MSK) scheme for the grid setting to reconstruct ESPs and fields data from QCArchive.

For the MSK shell grid points, I'd like to be able to pass two user-defined parameters:

1. A list of scaling factors or a spacing/increment factor to scale the VdW radii
2. A surface density - the number of points to generate per square angstrom of surface area

Thank you for looking into this!

**Comment by SimonBoothroyd** [comment]
@wwilla7 sorry for the delay in this, this should be supported in the next release. See `examples/qc-data-generation/generate-psi4.py` for details and let me know if you have any questions.
